//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagnifierApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagnifierApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Inspector is an example application on how to capture and process high resolution photos (resolution depends on device hardware)..
        /// </summary>
        public static string AboutPage_AboutRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_AboutRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a photo and slide your finger on the preview to bring up a loupe to zoom right into pixel perfect details in the photo. Reframe rectangular areas from photos and save lower resolution copies to the main Photos gallery while retaining the original maximum resolution photos hidden in Camera Roll for later use - for example for reframing the photo! Share photos as lower resolution copies to online services like Facebook and Twitter..
        /// </summary>
        public static string AboutPage_GuideRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_GuideRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://projects.developer.nokia.com/.
        /// </summary>
        public static string AboutPage_Hyperlink_Projects {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed and published by Nokia. All rights reserved..
        /// </summary>
        public static string AboutPage_LegalRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_LegalRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information and application source code go to {0}..
        /// </summary>
        public static string AboutPage_ProjectRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_ProjectRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPage_Title_Text {
            get {
                return ResourceManager.GetString("AboutPage_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Inspector version {0}.
        /// </summary>
        public static string AboutPage_VersionRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_VersionRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTO INSPECTOR.
        /// </summary>
        public static string App_Title_Text {
            get {
                return ResourceManager.GetString("App_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string CropPage_AcceptButton_Text {
            get {
                return ResourceManager.GetString("CropPage_AcceptButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        public static string InfoPage_ApertureTitleTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_ApertureTitleTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string InfoPage_DateTimeTitleTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_DateTimeTitleTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string InfoPage_DimensionsTitleTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_DimensionsTitleTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure time.
        /// </summary>
        public static string InfoPage_ExposureTimeTitleTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_ExposureTimeTitleTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string InfoPage_ExposureTimeValueFormatTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_ExposureTimeValueFormatTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string InfoPage_FlashTitleTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_FlashTitleTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash did fire.
        /// </summary>
        public static string InfoPage_FlashValueFiredTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_FlashValueFiredTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash did not fire.
        /// </summary>
        public static string InfoPage_FlashValueNotFiredTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_FlashValueNotFiredTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This photo does not seem to have any additional information..
        /// </summary>
        public static string InfoPage_GuideTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_GuideTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        public static string InfoPage_IsoTitleTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_IsoTitleTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string InfoPage_MakeTitleTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_MakeTitleTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string InfoPage_ModelTitleTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_ModelTitleTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string InfoPage_SoftwareTitleTextBlock_Text {
            get {
                return ResourceManager.GetString("InfoPage_SoftwareTitleTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo info.
        /// </summary>
        public static string InfoPage_Title_Text {
            get {
                return ResourceManager.GetString("InfoPage_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MagnifierPage_AboutMenuItem_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_AboutMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string MagnifierPage_CameraMenuItem_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_CameraMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reframe.
        /// </summary>
        public static string MagnifierPage_CropButton_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_CropButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos gallery.
        /// </summary>
        public static string MagnifierPage_GalleryMenuItem_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_GalleryMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, unable to read photo:(.
        /// </summary>
        public static string MagnifierPage_GalleryReadErrorMessageBox_Caption {
            get {
                return ResourceManager.GetString("MagnifierPage_GalleryReadErrorMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo you selected seems unreadable to me, care to try with another photo?.
        /// </summary>
        public static string MagnifierPage_GalleryReadErrorMessageBox_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_GalleryReadErrorMessageBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string MagnifierPage_InfoButton_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_InfoButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo stored in Camera Roll.
        /// </summary>
        public static string MagnifierPage_InformationTextBlock_CameraRollText {
            get {
                return ResourceManager.GetString("MagnifierPage_InformationTextBlock_CameraRollText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo stored in Saved Pictures.
        /// </summary>
        public static string MagnifierPage_InformationTextBlock_SavedPicturesText {
            get {
                return ResourceManager.GetString("MagnifierPage_InformationTextBlock_SavedPicturesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New photo (not saved).
        /// </summary>
        public static string MagnifierPage_InformationTextBlock_UnsavedText {
            get {
                return ResourceManager.GetString("MagnifierPage_InformationTextBlock_UnsavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local photos.
        /// </summary>
        public static string MagnifierPage_PhotosMenuItem_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_PhotosMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revert to original.
        /// </summary>
        public static string MagnifierPage_RevertMenuItem_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_RevertMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string MagnifierPage_SaveButton_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_SaveButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, unable to save to gallery:(.
        /// </summary>
        public static string MagnifierPage_SavePhotoErrorMessageBox_Caption {
            get {
                return ResourceManager.GetString("MagnifierPage_SavePhotoErrorMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems that saving the photo failed. If the device is connected to a computer, please disconnect it and try again..
        /// </summary>
        public static string MagnifierPage_SavePhotoErrorMessageBox_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_SavePhotoErrorMessageBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string MagnifierPage_ShareButton_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_ShareButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let&apos;s get going.
        /// </summary>
        public static string MagnifierPage_Title_Text {
            get {
                return ResourceManager.GetString("MagnifierPage_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PhotosPage_AboutMenuItem_Text {
            get {
                return ResourceManager.GetString("PhotosPage_AboutMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string PhotosPage_CameraButton_Text {
            get {
                return ResourceManager.GetString("PhotosPage_CameraButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete all.
        /// </summary>
        public static string PhotosPage_DeleteAllMenuItem_Text {
            get {
                return ResourceManager.GetString("PhotosPage_DeleteAllMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all photos?.
        /// </summary>
        public static string PhotosPage_DeleteAllMessageBox_Caption {
            get {
                return ResourceManager.GetString("PhotosPage_DeleteAllMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all high resolution photos saved in Photo Inspector&apos;s local storage?.
        /// </summary>
        public static string PhotosPage_DeleteAllMessageBox_Text {
            get {
                return ResourceManager.GetString("PhotosPage_DeleteAllMessageBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string PhotosPage_DeleteMenuItem_Text {
            get {
                return ResourceManager.GetString("PhotosPage_DeleteMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photos in Pictures library.
        ///
        ///Photos in Camera Roll and re-framed photos in Saved Pictures are displayed here..
        /// </summary>
        public static string PhotosPage_PickerGuideTextBlock_Text {
            get {
                return ResourceManager.GetString("PhotosPage_PickerGuideTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share....
        /// </summary>
        public static string PhotosPage_ShareMenuItem_Text {
            get {
                return ResourceManager.GetString("PhotosPage_ShareMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photos in Pictures library.
        ///
        ///Photos in Camera Roll and re-framed photos in Saved Pictures are displayed here. To access other photos tap the gallery button, or go capture new photos by tapping the camera button.
        ///
        ///Notice that if you delete photos captured by Photo Inspector from other applications, the corresponding high resolution photos will also be deleted automatically next time Photo Inspector is launched..
        /// </summary>
        public static string PhotosPage_StandaloneGuideTextBlock_Text {
            get {
                return ResourceManager.GetString("PhotosPage_StandaloneGuideTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        public static string PhotosPage_Title_Text {
            get {
                return ResourceManager.GetString("PhotosPage_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string ViewFinderPage_AboutMenuItem_Text {
            get {
                return ResourceManager.GetString("ViewFinderPage_AboutMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capture.
        /// </summary>
        public static string ViewfinderPage_CaptureButton_Text {
            get {
                return ResourceManager.GetString("ViewfinderPage_CaptureButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flash.
        /// </summary>
        public static string ViewfinderPage_FlashButton_Text {
            get {
                return ResourceManager.GetString("ViewfinderPage_FlashButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallery.
        /// </summary>
        public static string ViewfinderPage_GalleryButton_Text {
            get {
                return ResourceManager.GetString("ViewfinderPage_GalleryButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, unable to read photo:(.
        /// </summary>
        public static string ViewfinderPage_GalleryReadErrorMessageBox_Caption {
            get {
                return ResourceManager.GetString("ViewfinderPage_GalleryReadErrorMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo you selected seems unreadable to me, care to try with another photo?.
        /// </summary>
        public static string ViewfinderPage_GalleryReadErrorMessageBox_Text {
            get {
                return ResourceManager.GetString("ViewfinderPage_GalleryReadErrorMessageBox_Text", resourceCulture);
            }
        }
    }
}
